Repository k-mozzi/used_device_market_v2, pull requests merged in 2024-01, with the labels that each got.

#72 상품 목록, 찜 목록, 판매 목록에 상품이 없는 경우 기본 메시지가 출력되도록 설정
  src/main/java/teamproject/usedmarket/WebConfig.java
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/repository/mybatis/PagingMapper.java
  src/main/java/teamproject/usedmarket/service/EntityServiceV1.java
  src/main/java/teamproject/usedmarket/web/paging/EntityController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/PagingMapper.xml
  src/main/resources/templates/entities.html
  src/main/resources/templates/item/items.html
  src/main/resources/templates/members/myPage/memberLike.html
  src/main/resources/templates/members/myPage/memberSell.html
Labels: enhancement

#74 아이템 목록에서 최신순, 조회수순, 좋아요순으로 정렬하는 기능 구현
  src/main/java/teamproject/usedmarket/repository/ItemRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ItemMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisItemRepository.java
  src/main/java/teamproject/usedmarket/service/ItemService.java
  src/main/java/teamproject/usedmarket/service/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/teamproject/usedmarket/repository/mybatis/LikeMapper.xml
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/item/items.html
Labels: enhancement

#78 판매완료된 상품은 items.html에서 제외, 마이페이지의 판매목록에서 판매중, 판매완료 상태 구분
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/repository/MemberRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MemberMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisMemberRepository.java
  src/main/java/teamproject/usedmarket/service/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/members/myPage/memberSell.html
Labels: enhancement

#80 아이템 목록의 정렬 방식에 카테고리 셀렉트박스 추가
  src/main/java/teamproject/usedmarket/repository/ItemRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ItemMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisItemRepository.java
  src/main/java/teamproject/usedmarket/service/ItemService.java
  src/main/java/teamproject/usedmarket/service/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/templates/item/items.html
Labels: enhancement

#82 아이템 목록에 지역 셀렉트박스 추가
  src/main/java/teamproject/usedmarket/repository/ItemRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ItemMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisItemRepository.java
  src/main/java/teamproject/usedmarket/service/ItemService.java
  src/main/java/teamproject/usedmarket/service/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/templates/item/items.html
  src/main/resources/templates/members/myPage/memberSell.html
Labels: enhancement

#84 아이템 목록에 검색어를 통한 검색 기능 추가
  src/main/java/teamproject/usedmarket/repository/ItemRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ItemMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisItemRepository.java
  src/main/java/teamproject/usedmarket/service/ItemService.java
  src/main/java/teamproject/usedmarket/service/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/templates/item/items.html
Labels: enhancement

#86 아이템 목록에 상품 등록 버튼 생성, 아이템 이미지 테이블에 on delete cascade 옵션 추가해서 아이템이 삭제될 때 이미지도 같이 삭제되도록 변경
  src/main/resources/teamproject/usedmarket/repository/mybatis/ImageMapper.xml
  src/main/resources/templates/item/items.html
Labels: enhancement

#88 아이템 검증 구현, 관심상품 목록에서 판매완료 상품은 나오지 않도록 변경
  src/main/java/teamproject/usedmarket/domain/item/Item.java
  src/main/java/teamproject/usedmarket/domain/member/Member.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/application.properties
  src/main/resources/errors.properties
  src/main/resources/teamproject/usedmarket/repository/mybatis/LikeMapper.xml
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/item/addForm.html
Labels: enhancement, invalid

#90 카카오 지도 API를 이용해 아이템 등록할 때 원하는 거래장소에 마커를 생성할 수 있도록 구현
  src/main/java/teamproject/usedmarket/domain/item/Item.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/templates/item/addForm.html
  src/main/resources/templates/item/item.html
Labels: enhancement

#92 아이템 등록시 현재 로그인한 멤버의 지역에 따라 지도의 초기 마커 값이 다르게 설정되도록 구현
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/templates/item/addForm.html
  src/main/resources/templates/item/item.html
Labels: enhancement

#94 아이템 수정에서 지도의 마커 위치 변경할 수 있도록 구현
  src/main/java/teamproject/usedmarket/repository/ItemUpdateDto.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/templates/item/editForm.html
Labels: enhancement

#97 파일구조정리 및 필요없는 파일 삭제
  build.gradle
  src/main/java/teamproject/usedmarket/config/MyBatisConfig.java
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/config/WebSocketConfig.java
  src/main/java/teamproject/usedmarket/domain/chat/Chat.java
  src/main/java/teamproject/usedmarket/domain/chat/Room.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ChatMapper.java
  src/main/java/teamproject/usedmarket/service/ChatService.java
  src/main/java/teamproject/usedmarket/service/image/ImageService.java
  src/main/java/teamproject/usedmarket/service/image/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/service/item/ItemService.java
  src/main/java/teamproject/usedmarket/service/item/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/service/like/LikeService.java
  src/main/java/teamproject/usedmarket/service/like/LikeServiceV1.java
  src/main/java/teamproject/usedmarket/service/login/LoginService.java
  src/main/java/teamproject/usedmarket/web/chat/ChatController.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/itemimage/ItemImageController.java
  src/main/java/teamproject/usedmarket/web/login/LoginController.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/application.properties
  src/main/resources/teamproject/usedmarket/repository/mybatis/ChatMapper.xml
  src/main/resources/templates/chat/chatPopup.html
  src/main/resources/templates/item/item.html
Labels: enhancement

#99 댓글 작성, 삭제 기능 구현
  src/main/java/teamproject/usedmarket/domain/comment/Comment.java
  src/main/java/teamproject/usedmarket/repository/CommentRepository.java
  src/main/java/teamproject/usedmarket/repository/CommentUpdateDto.java
  src/main/java/teamproject/usedmarket/repository/mybatis/CommentMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisCommentRepository.java
  src/main/java/teamproject/usedmarket/service/comment/CommentService.java
  src/main/java/teamproject/usedmarket/service/comment/CommentServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/CommentMapper.xml
  src/main/resources/templates/item/item.html
Labels: enhancement

#101 댓글에 대한 답글 기능 구현: 댓글 주인과 상품 주인만 등록/조회 가능
  src/main/java/teamproject/usedmarket/domain/comment/Comment.java
  src/main/java/teamproject/usedmarket/repository/CommentRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/CommentMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisCommentRepository.java
  src/main/java/teamproject/usedmarket/service/comment/CommentService.java
  src/main/java/teamproject/usedmarket/service/comment/CommentServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/CommentMapper.xml
  src/main/resources/templates/item/item.html
Labels: enhancement

#103 회원 수정 구현, 아이템 수정 폼에 required 옵션 추가
  src/main/java/teamproject/usedmarket/repository/MemberRepository.java
  src/main/java/teamproject/usedmarket/repository/MemberUpdateDto.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MemberMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisMemberRepository.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/item/editForm.html
  src/main/resources/templates/members/editMemberForm.html
Labels: enhancement

#105 회원 수정 후 세션 갱신
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
Labels: invalid

#109 2
  src/main/resources/templates/item/item.html
Labels: enhancement

#111 2
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/item/item.html
  src/main/resources/templates/members/myPage.html
  src/main/resources/templates/members/myPage/memberBuy.html
  src/main/resources/templates/popup/purchasePopup.html
Labels: enhancement

#113 2
  src/main/java/teamproject/usedmarket/repository/ItemRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/ItemMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisItemRepository.java
  src/main/java/teamproject/usedmarket/service/item/ItemService.java
  src/main/java/teamproject/usedmarket/service/item/ItemServiceV1.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/item/item.html
  src/main/resources/templates/members/myPage/memberBuy.html
  src/main/resources/templates/popup/purchasePopup.html
Labels: enhancement

#115 디자인 통일
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/repository/MemberRepository.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MemberMapper.java
  src/main/java/teamproject/usedmarket/repository/mybatis/MyBatisMemberRepository.java
  src/main/java/teamproject/usedmarket/service/image/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/teamproject/usedmarket/repository/mybatis/ItemMapper.xml
  src/main/resources/teamproject/usedmarket/repository/mybatis/MemberMapper.xml
  src/main/resources/templates/fragments/bodyHeader.html
  src/main/resources/templates/fragments/footer.html
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/home.html
  src/main/resources/templates/item/addForm.html
  src/main/resources/templates/item/editForm.html
  src/main/resources/templates/item/items.html
  src/main/resources/templates/loginHome.html
  src/main/resources/templates/members/addMemberForm.html
  src/main/resources/templates/members/editMemberForm.html
  src/main/resources/templates/members/members.html
  src/main/resources/templates/members/myPage.html
  src/main/resources/templates/members/myPage/memberBuy.html
  src/main/resources/templates/members/myPage/memberInfo.html
  src/main/resources/templates/members/myPage/memberLike.html
  src/main/resources/templates/members/myPage/memberSell.html
Labels: enhancement

#117 아이템 상세 폼(item.html) 수정
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/templates/item/item.html
  src/main/resources/templates/item/items.html
Labels: enhancement

#119 타인 계정 삭제 방지 로직 구현, 타인 게시물 수정 및 상제 방지 로직 부활시킴
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/templates/item/items.html
  src/main/resources/templates/loginHome.html
Labels: enhancement

#121 Asd
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/service/image/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/purchase/PurchaseController.java
  src/main/resources/templates/fragments/header.html
  src/main/resources/templates/item/addForm.html
  src/main/resources/templates/item/editForm.html
  src/main/resources/templates/item/item.html
  src/main/resources/templates/popup/purchasePopup.html
Labels: enhancement

#123 등록, 수정 검증 수정
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/repository/ItemUpdateDto.java
  src/main/java/teamproject/usedmarket/service/image/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/errors.properties
  src/main/resources/templates/item/addForm.html
  src/main/resources/templates/item/editForm.html
Labels: invalid

#125 아이템 삭제, 회원 탈퇴시 alert 창 뜨도록 변경
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/java/teamproject/usedmarket/web/member/MemberController.java
  src/main/resources/templates/item/item.html
  src/main/resources/templates/members/myPage/memberInfo.html
Labels: enhancement

#132 2
  build.gradle
  src/main/java/teamproject/usedmarket/config/S3Config.java
  src/main/java/teamproject/usedmarket/config/WebMvcConfig.java
  src/main/java/teamproject/usedmarket/service/image/ImageServiceV1.java
  src/main/java/teamproject/usedmarket/web/item/ItemController.java
  src/main/resources/application.properties
  src/main/resources/teamproject/usedmarket/repository/mybatis/ImageMapper.xml
  src/main/resources/templates/item/editForm.html
  src/main/resources/templates/item/item.html
  src/main/resources/templates/item/items.html
  src/main/resources/templates/members/myPage/memberBuy.html
  src/main/resources/templates/members/myPage/memberSell.html
Labels: enhancement
